config/routes.rb
Rails.application.routes.draw do

  root to: 'manufacturers#index'

  resources :manufacturers

  resources :cars

end

app/models/car.rb
class Car < ActiveRecord::Base
  belongs_to :manufacturer

  validates_presence_of :manufacturer_id, :color, :year, :mileage
  validates :year, length: { is: 4 }, on: :create
  validates_numericality_of :year, greater_than: 1919
  validates_numericality_of :year, less_than: Time.now.year + 1
end

app/models/manufacturer.rb
class Manufacturer < ActiveRecord::Base
  has_many :cars

  validates_presence_of :name
  validates_presence_of :country
  validates_uniqueness_of :name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  def index
    @cars = Car.all.limit(10)
  end

  def new
    @car = Car.new
  end

  def create
    @car = Car.new(car_attr)

    if @car.save
      flash[:notice] = 'Success! Car added!'
      redirect_to cars_path
    else
      flash[:notice] = 'Sorry! The car could not be saved!'
      render :new
    end
  end

  private

  def car_attr
    params.require(:car).permit(:manufacturer_id, :color, :year, :mileage, :description)
  end
end

app/controllers/manufacturers_controller.rb
class ManufacturersController < ApplicationController
  def index
    @manufacturers = Manufacturer.all
  end

  def new
    @manufacturer = Manufacturer.new
  end

  def create
    @manufacturer = Manufacturer.new(manufacturer_params)

    if @manufacturer.save
      flash[:notice] = 'Success!'
      redirect_to manufacturers_path
    else
      flash[:notice] = 'Please try again!'
      render :new
    end
  end

  private

  def manufacturer_params
    params.require(:manufacturer).permit(:name, :country)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cars/index.html.erb
<table class="table table-hover">
  <thead>
    <tr>
      <th>Manufacturer</th>
      <th>Color</th>
      <th>Year</th>
      <th>Mileage</th>
      <th>Description</th>
    </tr>
  </thead>
  <% @cars.each do |c| %>
    <tr>
      <td><%= c.manufacturer.name %></td>
      <td><%= c.color %></td>
      <td><%= c.year %></td>
      <td><%= c.mileage %></td>
      <td><%= c.description %></td>
    </tr>
  <% end %>
</table>

app/views/cars/new.html.erb
<%= form_for @car do |f| %>
  <h2 class="form-signin-heading">Add a car</h2>
  <% if @car.errors.any? %>
    <ul>
      <% @car.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  <% end %>

  <%= f.collection_select :manufacturer_id, Manufacturer.all, :id, :name, {include_blank: 'Manufacturer'},class: 'form-control'  %>
  <br>
  <%= f.text_field :color, class: 'form-control', placeholder: 'Color' %>
  <br>
  <%= f.text_field :year, class: 'form-control', placeholder: 'Year' %>
  <br>
  <%= f.text_field :mileage, class: 'form-control', placeholder: 'Mileage' %>
  <br>
  <%= f.text_field :description, class: 'form-control', placeholder: 'Description' %>
  <br>
  <%= f.submit 'Add Car', class: 'btn btn-default' %>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CarListing</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="navbar navbar-inverse navbar-static-top" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">Car listings</a>
      </div>
      <div class="navbar-collapse collapse">
        <ul class="nav navbar-nav">
          <li><%= link_to 'Cars', cars_path %></li>
          <li><%= link_to 'Add a car', new_car_path %></li>
          <li><%= link_to 'Manufacturers', manufacturers_path %></li>
          <li><%= link_to 'Add a manufacturer', new_manufacturer_path %></li>
        </ul>
      </div>
    </div>
  </div>


  <div class="container">
    <% if flash.any? %>
      <div class="alert alert-info">
        <strong>
          <%= flash[:notice] %>
          <%= flash[:alert] %>
        </strong>
      </div>
    <% end %>

    <%= yield %>
  </div>

</body>
</html>

app/views/manufacturers/index.html.erb
<table class="table table-hover">
  <thead>
    <tr>
      <th>Manufacturer</th>
      <th>Country</th>
    </tr>
  </thead>
  <% @manufacturers.each do |m| %>
    <tr>
      <td><%= m.name %></td>
      <td><%= m.country %></td>
    </tr>
  <% end %>
</table>

app/views/manufacturers/new.html.erb
<%= form_for @manufacturer do |f| %>
  <% if @manufacturer.errors.any? %>
    <ul>
      <% @manufacturer.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  <% end %>

  <%= f.text_field :name, class: 'form-control', placeholder: 'Name' %>
  <br>
  <%= f.text_field :country, class: 'form-control', placeholder: 'Country' %>
  <br>
  <%= f.submit 'Add Manufacturer', class: 'btn btn-default' %>

<% end %>